services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: jobscoper-frontend:latest  # Tag for the frontend image
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jobscoper-backend:latest  # Tag for the backend image
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      FLASK_ENV: production